[build]
builder = "nixpacks"
buildCommand = "composer install"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 60
healthcheckInterval = 15 