name = "unidad-espiritu-santo"
type = "javascript"
account_id = "your-account-id"
workers_dev = true
route = ""
zone_id = "your-zone-id"

[site]
bucket = "./public" # or your static assets directory
entry-point = "."

[build]
command = "" # e.g., npm run build
watch_dir = "src"
