[build]
command = ""
upload_dir = "."  # Ahora los archivos están en el mismo directorio que wrangler.toml

[pages]
name = "unidad-espiritu-santo"
production_branch = "main"

[env.production]
compatibility_date = "2024-05-06"

# Reemplazar con tu account_id de Cloudflare (encontrarlo en Dashboard -> Workers & Pages -> Account ID)
account_id = "TU_ACCOUNT_ID"